security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: ~
#            form_login:
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#            http_basic:
#                realm: "Please authenticate"
            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_BB_ADMIN }
        - { path: ^/, roles: [ROLE_BB_AUTHENTICATED_USER] }
        # Include the following line to also secure the /gui path itself
        #- { path: ^/gui$, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_BB_RESOURCE: [ROLE_BB_AUTHENTICATED_USER]
        ROLE_BB_CLIENT: [ROLE_BB_AUTHENTICATED_USER]
        ROLE_BB_ADMIN: [ROLE_BB_RESOURCE]
        ROLE_BB_SUPER: [ROLE_BB_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
